version: "3.9"

services:

  backend:
    build: ./galaxy-party-backend
    container_name: backend-staging
    ports:
      - "8081:8080"
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: stg

  websocket:
    build: ./galaxy-party-websocket
    container_name: websocket-staging
    ports:
      - "4001:4000"
    restart: unless-stopped
    env_file:
      - ./galaxy-party-websocket/.env.staging