UPDATE questions SET display_answer = 'Louis XIV' WHERE label = 'Quel roi français était surnommé le Roi Soleil ?';
UPDATE questions SET display_answer = 'Paris' WHERE label = 'Quelle est la capitale de la France ?';
UPDATE questions SET display_answer = '3' WHERE label = 'Combien de couleurs composent le drapeau français ?';
UPDATE questions SET display_answer = 'La Loire' WHERE label = 'Quel est le plus long fleuve de France ?';
UPDATE questions SET display_answer = '1789' WHERE label = 'En quelle année a eu lieu la Révolution française ?';
UPDATE questions SET display_answer = 'Au' WHERE label = 'Quel est le symbole chimique de l''or ?';
UPDATE questions SET display_answer = '8' WHERE label = 'Combien de planètes compte notre système solaire ?';
UPDATE questions SET display_answer = 'La baleine bleue' WHERE label = 'Quel est l''animal le plus grand du monde ?';
UPDATE questions SET display_answer = 'Léonard de Vinci' WHERE label = 'Qui a peint la Joconde ?';
UPDATE questions SET display_answer = 'H₂O' WHERE label = 'Quelle est la formule chimique de l''eau ?';
UPDATE questions SET display_answer = 'La Chine' WHERE label = 'Dans quel pays se trouve la Grande Muraille ?';
UPDATE questions SET display_answer = 'L''Asie' WHERE label = 'Quel est le continent le plus grand du monde ?';
UPDATE questions SET display_answer = '6' WHERE label = 'Combien de côtés a un hexagone ?';
UPDATE questions SET display_answer = 'L''Inde' WHERE label = 'Quel est le pays le plus peuplé du monde ?';
UPDATE questions SET display_answer = 'Mercure' WHERE label = 'Quelle planète est la plus proche du Soleil ?';
UPDATE questions SET display_answer = 'Victor Hugo' WHERE label = 'Qui a écrit Les Misérables ?';
UPDATE questions SET display_answer = 'Madrid' WHERE label = 'Quelle est la capitale de l''Espagne ?';
UPDATE questions SET display_answer = 'L''Everest' WHERE label = 'Quel est le plus haut sommet du monde ?';
UPDATE questions SET display_answer = '11' WHERE label = 'Combien de joueurs composent une équipe de football ?';
UPDATE questions SET display_answer = 'Fe' WHERE label = 'Quel est le symbole chimique du fer ?';
UPDATE questions SET display_answer = 'Paris' WHERE label = 'Dans quelle ville se trouve la Tour Eiffel ?';
UPDATE questions SET display_answer = 'Alexander Fleming' WHERE label = 'Qui a découvert la pénicilline ?';
UPDATE questions SET display_answer = 'Berlin' WHERE label = 'Quelle est la capitale de l''Allemagne ?';
UPDATE questions SET display_answer = 'L''océan Pacifique' WHERE label = 'Quel océan est le plus grand ?';
UPDATE questions SET display_answer = '24' WHERE label = 'Combien d''heures compte une journée ?';
UPDATE questions SET display_answer = 'L''or' WHERE label = 'Quel est le métal le plus précieux ?';
UPDATE questions SET display_answer = 'Beethoven' WHERE label = 'Qui a composé la Symphonie n°5 ?';
UPDATE questions SET display_answer = 'Rome' WHERE label = 'Quelle est la capitale de l''Italie ?';
UPDATE questions SET display_answer = '1 000' WHERE label = 'Combien de grammes dans un kilogramme ?';
UPDATE questions SET display_answer = 'Le Sahara' WHERE label = 'Quel est le plus grand désert du monde ?';
UPDATE questions SET display_answer = '1969' WHERE label = 'En quelle année l''homme a-t-il marché sur la Lune pour la première fois ?';
UPDATE questions SET display_answer = 'Le Nil' WHERE label = 'Quel est le fleuve le plus long du monde ?';
UPDATE questions SET display_answer = 'William Shakespeare' WHERE label = 'Qui a écrit Hamlet ?';
UPDATE questions SET display_answer = 'Tokyo' WHERE label = 'Quelle est la capitale du Japon ?';
UPDATE questions SET display_answer = '60' WHERE label = 'Combien de secondes dans une minute ?';
UPDATE questions SET display_answer = 'Na' WHERE label = 'Quel est le symbole chimique du sodium ?';
UPDATE questions SET display_answer = 'Isaac Newton' WHERE label = 'Qui a théorisé la gravitation universelle ?';
UPDATE questions SET display_answer = 'Brasília' WHERE label = 'Quelle est la capitale du Brésil ?';
UPDATE questions SET display_answer = 'Le Vatican' WHERE label = 'Quel est le plus petit pays du monde ?';
UPDATE questions SET display_answer = '60' WHERE label = 'Combien de minutes dans une heure ?';
UPDATE questions SET display_answer = 'Miguel de Cervantes' WHERE label = 'Qui a écrit Don Quichotte ?';
UPDATE questions SET display_answer = 'O' WHERE label = 'Quel est le symbole chimique de l''oxygène ?';
UPDATE questions SET display_answer = 'Canberra' WHERE label = 'Quelle est la capitale de l''Australie ?';
UPDATE questions SET display_answer = '6' WHERE label = 'Combien de faces a un cube ?';
UPDATE questions SET display_answer = 'Alexander Graham Bell' WHERE label = 'Qui a inventé le téléphone ?';
UPDATE questions SET display_answer = 'Moscou' WHERE label = 'Quelle est la capitale de la Russie ?';
UPDATE questions SET display_answer = 'La Russie' WHERE label = 'Quel est le plus grand pays du monde en superficie ?';
UPDATE questions SET display_answer = '5' WHERE label = 'Combien de joueurs dans une équipe de basketball ?';
UPDATE questions SET display_answer = 'Michel-Ange' WHERE label = 'Qui a peint la Chapelle Sixtine ?';
UPDATE questions SET display_answer = 'Ottawa' WHERE label = 'Quelle est la capitale du Canada ?';
UPDATE questions SET display_answer = 'C' WHERE label = 'Quel est le symbole chimique du carbone ?';
UPDATE questions SET display_answer = '6' WHERE label = 'Combien de cordes a une guitare classique ?';
UPDATE questions SET display_answer = 'Thomas Edison' WHERE label = 'Qui a inventé l''ampoule électrique ?';
UPDATE questions SET display_answer = 'Pékin' WHERE label = 'Quelle est la capitale de la Chine ?';
UPDATE questions SET display_answer = 'L''hydrogène' WHERE label = 'Quel est l''élément le plus abondant dans l''univers ?';
UPDATE questions SET display_answer = '32' WHERE label = 'Combien de dents a un adulte humain ?';
UPDATE questions SET display_answer = 'William Shakespeare' WHERE label = 'Qui a écrit Roméo et Juliette ?';
UPDATE questions SET display_answer = 'Buenos Aires' WHERE label = 'Quelle est la capitale de l''Argentine ?';
UPDATE questions SET display_answer = 'La mer Caspienne' WHERE label = 'Quel est le plus grand lac du monde ?';
UPDATE questions SET display_answer = '1815' WHERE label = 'En quelle année Napoléon a-t-il été exilé à Sainte-Hélène ?';
UPDATE questions SET display_answer = '206' WHERE label = 'Combien d''os compte le corps humain adulte ?';
UPDATE questions SET display_answer = 'Homère' WHERE label = 'Qui a écrit L''Odyssée ?';
UPDATE questions SET display_answer = 'New Delhi' WHERE label = 'Quelle est la capitale de l''Inde ?';
UPDATE questions SET display_answer = 'Ag' WHERE label = 'Quel est le symbole chimique de l''argent ?';
UPDATE questions SET display_answer = '15' WHERE label = 'Combien de joueurs dans une équipe de rugby à XV ?';
UPDATE questions SET display_answer = 'Albert Einstein' WHERE label = 'Qui a développé la théorie de la relativité ?';
UPDATE questions SET display_answer = 'Mexico City' WHERE label = 'Quelle est la capitale du Mexique ?';
UPDATE questions SET display_answer = 'La peau' WHERE label = 'Quel est le plus grand organe du corps humain ?';
UPDATE questions SET display_answer = '88' WHERE label = 'Combien de touches compte un piano standard ?';
UPDATE questions SET display_answer = 'Antoine de Saint-Exupéry' WHERE label = 'Qui a écrit Le Petit Prince ?';
UPDATE questions SET display_answer = 'Le Caire' WHERE label = 'Quelle est la capitale de l''Égypte ?';
UPDATE questions SET display_answer = 'Pb' WHERE label = 'Quel est le symbole chimique du plomb ?';
UPDATE questions SET display_answer = '1914' WHERE label = 'En quelle année a débuté la Première Guerre mondiale ?';
UPDATE questions SET display_answer = '7' WHERE label = 'Combien de continents y a-t-il sur Terre ?';
UPDATE questions SET display_answer = 'Johannes Gutenberg' WHERE label = 'Qui a inventé l''imprimerie ?';
UPDATE questions SET display_answer = 'Ankara' WHERE label = 'Quelle est la capitale de la Turquie ?';
UPDATE questions SET display_answer = 'L''azote' WHERE label = 'Quel est le gaz le plus présent dans l''atmosphère terrestre ?';
UPDATE questions SET display_answer = '5' WHERE label = 'Combien de doigts a une main humaine ?';
UPDATE questions SET display_answer = 'Gustave Flaubert' WHERE label = 'Qui a écrit Madame Bovary ?';
UPDATE questions SET display_answer = 'Washington D.C.' WHERE label = 'Quelle est la capitale des États-Unis ?';
UPDATE questions SET display_answer = '46' WHERE label = 'Quel est le nombre de chromosomes dans une cellule humaine normale ?';
UPDATE questions SET display_answer = 'Auguste Rodin' WHERE label LIKE 'Qui a sculp%té Le Penseur ?';
UPDATE questions SET display_answer = 'Athènes' WHERE label = 'Quelle est la capitale de la Grèce ?';
UPDATE questions SET display_answer = '366' WHERE label = 'Combien de jours compte une année bissextile ?';
UPDATE questions SET display_answer = 'Marie Curie' WHERE label = 'Qui a découvert la radioactivité ?';
UPDATE questions SET display_answer = 'Séoul' WHERE label = 'Quelle est la capitale de la Corée du Sud ?';
UPDATE questions SET display_answer = 'Le guépard' WHERE label = 'Quel est le plus rapide des animaux terrestres ?';
UPDATE questions SET display_answer = '7' WHERE label = 'Combien de notes dans une gamme musicale ?';
UPDATE questions SET display_answer = 'Fiodor Dostoïevski' WHERE label = 'Qui a écrit Crime et Châtiment ?';
UPDATE questions SET display_answer = 'Stockholm' WHERE label = 'Quelle est la capitale de la Suède ?';
UPDATE questions SET display_answer = 'K' WHERE label = 'Quel est le symbole chimique du potassium ?';
UPDATE questions SET display_answer = '1889' WHERE label = 'En quelle année a été construite la Tour Eiffel ?';
UPDATE questions SET display_answer = '6' WHERE label = 'Combien de joueurs dans une équipe de volley-ball ?';
UPDATE questions SET display_answer = 'Vincent Van Gogh' WHERE label = 'Qui a peint La Nuit étoilée ?';
UPDATE questions SET display_answer = 'Oslo' WHERE label = 'Quelle est la capitale de la Norvège ?';
UPDATE questions SET display_answer = 'Le fémur' WHERE label = 'Quel est l''os le plus long du corps humain ?';
UPDATE questions SET display_answer = '4' WHERE label = 'Combien de faces a un tétraèdre ?';
UPDATE questions SET display_answer = 'Albert Camus' WHERE label = 'Qui a écrit L''Étranger ?';
UPDATE questions SET display_answer = 'Varsovie' WHERE label = 'Quelle est la capitale de la Pologne ?';
UPDATE questions SET display_answer = 'Cu' WHERE label = 'Quel est le symbole chimique du cuivre ?';
UPDATE questions SET display_answer = '1945' WHERE label = 'En quelle année s''est terminée la Seconde Guerre mondiale ?';
UPDATE questions SET display_answer = '7' WHERE label = 'Combien de couleurs y a-t-il dans un arc-en-ciel ?';
UPDATE questions SET display_answer = 'Steve Jobs' WHERE label = 'Qui a fondé la société Apple ?';
UPDATE questions SET display_answer = 'Amsterdam' WHERE label = 'Quelle est la capitale des Pays-Bas ?';
UPDATE questions SET display_answer = 'L''éléphant d''Afrique' WHERE label = 'Quel est le plus grand mammifère terrestre ?';
UPDATE questions SET display_answer = '1' WHERE label = 'Combien de paires de chromosomes sexuels l''être humain possède-t-il ?';
UPDATE questions SET display_answer = 'Samuel Beckett' WHERE label = 'Qui a écrit En attendant Godot ?';
UPDATE questions SET display_answer = 'Lisbonne' WHERE label = 'Quelle est la capitale du Portugal ?';
