spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/galaxy_party_db}
    username: ${DATABASE_USER:admin}
    password: ${DATABASE_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    database: POSTGRESQL
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/galaxy_party_db}
    password: ${DATABASE_PASSWORD:admin}
    user: ${DATABASE_USER:admin}
  application:
    name: backend

server:
  servlet:
    context-path: "/api"
  port: ${PORT:8080}

app:
  jwt:
    secret: ${JWT_SECRET:VXZhVYwIEbxY4yQ6k4iiu0QegufOMA95/GgbVPUccaxfjxNJ8zcXTuvmluLARjyM7ieR10YCFl2KvfeDruY7rQ==}
    issuer: galaxy-party
    access-ttl: 15m
    refresh-ttl: 7d
  ws:
    service-token: ${WS_SERVICE_TOKEN:L8KlsEj6YGT1Ajz36cGbX4QOyXv9lbAqIfM7JlPVhKg0OanoVe6dVoOrsotOc2Sj}
  cookie:
    secure: ${COOKIE_SECURE:false}
    same-site: ${COOKIE_SAME_SITE:Lax}